DROP TABLE IF EXISTS items       CASCADE;
DROP TABLE IF EXISTS payments    CASCADE;
DROP TABLE IF EXISTS deliveries  CASCADE;
DROP TABLE IF EXISTS orders      CASCADE;
DROP FUNCTION IF EXISTS trg_set_timestamp() CASCADE;
